- name: .gitattributes
  format: text
  includes:
  - .gitattributes
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/dist/** -diff linguist-generated=true',
            '',
        ].join('\n')
- name: .gitignore
  format: text
  includes:
  - .gitignore
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/build',
            '/coverage',
            '',
        ].join('\n')
