repositories:
- remal-github-actions/template-typescript

transformations:
- name: .gitattributes
  format: text
  includes:
  - .gitattributes
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/dist/** -diff linguist-generated=true',
            '',
        ].join('\n')
- name: .gitignore
  format: text
  includes:
  - .gitignore
  script: |
    return content
        + [
            '',
            '# Remal GitHub actions:',
            '/build',
            '/coverage',
            '',
        ].join('\n')
- name: .github/sync-with-template.yml
  format: yaml
  includes:
  - .github/sync-with-template.yml
  script: |
    ;[
      'tsconfig-generate-app.js',
      'update-node-version-in-files.js',
    ].forEach(path => {
      if (!content.includes.includes(path)) {
        content.includes.push(path)
      }
    })
    return content
- name: Renovate
  format: text
  includes:
  - .github/renovate.json5
  replaceWithText: |
    {
      $schema: "https://docs.renovatebot.com/renovate-schema.json",
      extends: ["github>remal/renovate-config:global"],

      "git-submodules": {
        enabled: false, // This is in beta for now, so let's use Dependabot to update Git submodules
      },

      //constraintsFiltering: 'strict',

      node: {
        enabled: false,
      },

      js: {
        packageRules: [
          {
            matchPackageNames: ['@types/node'],
            extends: ["github>remal/renovate-config:disable-major-updates"],
          },
        ],
      },

      lockFileMaintenance: {
        enabled: true,
      },

      // $$$sync-with-template-modifiable: local $$$
      // $$$sync-with-template-modifiable-end$$$
    }
