name: validate

on:
  workflow_call:
    secrets:
      PUSH_BACK_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  validate:
    if: {{github.event_name == 'push' && github.ref == 'refs/heads/main' && env.PUSH_BACK_TOKEN}}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Run current action
      env:
        PUSH_BACK_TOKEN: {{secrets.PUSH_BACK_TOKEN}}
      uses: ../../
      with:
        githubToken: {{env.PUSH_BACK_TOKEN}}
