name: build

on:
  push:
    branches:
    - main
  pull_request: { }

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[skip ci]') && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
}}
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Read action's Node.js version
      id: readNodeVersion
      run: |
        USING=$( yq .runs.using ./action.yml )
        if ! [[ "$USING" =~ ^node[0-9]+$ ]]; then
          echo "::error::action.yml: .runs.using doesn't start with 'node': '$USING'"
          exit 1
        fi
        echo "::set-output name=result::${USING:4}"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{steps.readNodeVersion.outputs.result}}'


    - name: node_modules cache
      uses: actions/cache@v3
      with:
        key: ${{runner.os}}-node_modules-${{steps.readNodeVersion.outputs.result}}-${{hashFiles('package.json', '*.lock')}}
        path: |
          node_modules


    - name: Install dependencies
      run: |
        cat ./package.json | jq '.engines.node = ">=${{steps.readNodeVersion.outputs.result}}"' > ./package.json
        cat ./package.json
        yarn install

    - name: Build
      run: |
        npm run build


    - name: Validate
      uses: ./.github/workflows-includes/validate.yml


    - name: Push back
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') && env.PUSH_BACK_TOKEN}}
      uses: remal-github-actions/push-back@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        message: '[push-back] Push-back updated files during build'


    - name: Read version
      id: readVersion
      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main'}}
      uses: remal-github-actions/read-nodejs-package-version@v1

    - name: Create tag
      env:
        PUSH_BACK_TOKEN: ${{secrets.PUSH_BACK_TOKEN}}
      if: ${{github.event_name == 'push' && github.ref == 'refs/heads/main' && env.PUSH_BACK_TOKEN}}
      uses: remal-github-actions/create-tag@v1
      with:
        githubToken: ${{env.PUSH_BACK_TOKEN}}
        tagName: 'v${{steps.readVersion.outputs.majorVersion}}'
        forcePush: 'true'
